<script setup lang="ts">
import { ref, computed } from 'vue'
import { Upload, Download, Loader2, Trash2, RotateCw } from 'lucide-vue-next'
const files=ref<File[]>([]), quality=ref(85), width=ref(0), height=ref(0), format=ref('jpg'), rotate=ref(0), busy=ref(false), error=ref(''), resultUrl=ref('')
const totalSize=computed(()=>files.value.reduce((n,f)=>n+f.size,0))
const sizeText=(n:number)=>n<1024*1024?(n/1024).toFixed(1)+' KB':(n/1024/1024).toFixed(2)+' MB'
function add(list:FileList|null){if(!list)return;const incoming=Array.from(list).filter(f=>f.type.startsWith('image/'));files.value=[...files.value,...incoming].slice(0,50);error.value='';resultUrl.value=''}
function remove(i:number){files.value.splice(i,1)}
async function run(){if(!files.value.length){error.value='请先选择图片';return}busy.value=true;error.value='';try{const form=new FormData();files.value.forEach(f=>form.append('files',f));const qs=new URLSearchParams({format:format.value,quality:String(quality.value),width:String(width.value),height:String(height.value),rotate:String(rotate.value)});const r=await fetch('http://localhost:8080/api/image/batch/process?'+qs,{method:'POST',body:form});if(!r.ok)throw new Error(await r.text()||'批量处理失败');resultUrl.value=URL.createObjectURL(await r.blob())}catch(e){error.value=e instanceof Error?e.message:'批量处理失败'}finally{busy.value=false}}
</script>
<template><div class="batch"><div class="head"><div class="icon">🖼️</div><div><h1>批量图片处理</h1><p>一次最多处理 50 张图片，完成后打包成 ZIP 下载。</p></div></div><label class="drop"><Upload :size="25"/><b>点击或拖拽图片到这里</b><span>支持 JPG、PNG、WebP · 最多 50 张</span><input type="file" accept="image/*" multiple hidden @change="add(($event.target as HTMLInputElement).files)"/></label><div v-if="files.length" class="summary"><strong>{{files.length}} 张图片</strong><span>原始大小 {{sizeText(totalSize)}}</span><button @click="files=[]"><Trash2 :size="14"/>清空</button></div><div v-if="files.length" class="list"><div v-for="(f,i) in files" :key="i" class="file"><img :src="URL.createObjectURL(f)"/><div><b>{{f.name}}</b><span>{{sizeText(f.size)}}</span></div><button @click="remove(i)">×</button></div></div><div class="options"><label>输出格式<select v-model="format"><option value="jpg">JPG</option><option value="png">PNG</option><option value="webp">WebP</option></select></label><label>质量 <input v-model.number="quality" type="number" min="10" max="100"/>%</label><label>宽度 <input v-model.number="width" type="number" min="0" placeholder="原尺寸"/></label><label>高度 <input v-model.number="height" type="number" min="0" placeholder="原尺寸"/></label><label>旋转 <select v-model.number="rotate"><option :value="0">0°</option><option :value="90">90°</option><option :value="180">180°</option><option :value="270">270°</option></select></label></div><div v-if="error" class="error">{{error}}</div><div class="actions"><button class="primary" :disabled="busy" @click="run"><Loader2 v-if="busy" class="spin"/><span>{{busy?'处理中…':'批量处理并打包 ZIP'}}</span></button><a v-if="resultUrl" class="download" :href="resultUrl" download="officebox-images.zip"><Download :size="16"/>下载 ZIP</a></div></div></template>
<style scoped>.batch{max-width:900px;margin:auto;padding:30px 24px}.head{display:flex;gap:14px;align-items:center;margin-bottom:22px}.icon{width:46px;height:46px;border-radius:12px;background:#e8f2ff;display:grid;place-items:center}.head h1{font-size:22px;margin:0 0 4px}.head p{font-size:12px;color:#8991a2;margin:0}.drop{min-height:170px;border:1.5px dashed #ccd1df;border-radius:15px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;color:#4382d4;background:#fbfdff;cursor:pointer}.drop b{font-size:13px;color:#343c4c}.drop span{font-size:11px;color:#969dad}.summary{display:flex;align-items:center;gap:12px;margin:16px 0 10px;font-size:12px}.summary span{color:#8991a2;flex:1}.summary button,.file button{border:0;background:transparent;cursor:pointer;color:#858da0;display:flex;gap:5px;align-items:center}.list{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;max-height:260px;overflow:auto}.file{display:flex;align-items:center;gap:9px;padding:8px;border:1px solid #e7e9ef;border-radius:9px}.file img{width:42px;height:42px;object-fit:cover;border-radius:6px}.file div{display:flex;flex-direction:column;min-width:0;flex:1}.file b{font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.file span{font-size:10px;color:#9aa1af;margin-top:3px}.options{display:flex;flex-wrap:wrap;gap:10px;margin-top:16px;padding:15px;border:1px solid #e7e9ef;border-radius:10px}.options label{font-size:11px;color:#687083;display:flex;align-items:center;gap:6px}.options input,.options select{width:95px;border:1px solid #dfe2ea;border-radius:7px;padding:7px;outline:none}.error{margin-top:14px;background:#fff0f0;color:#c84f5a;padding:10px;border-radius:8px;font-size:12px}.actions{display:flex;gap:9px;margin-top:20px}.primary,.download{border:0;border-radius:9px;padding:10px 15px;display:flex;align-items:center;gap:7px;font-size:12px;font-weight:650;text-decoration:none;cursor:pointer}.primary{background:#6659df;color:white}.download{background:#eaf7ef;color:#348354}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:600px){.list{grid-template-columns:1fr}.options{display:grid;grid-template-columns:1fr 1fr}}
</style>
