<script setup lang="ts">
import { ref, computed, onBeforeUnmount } from 'vue'
import { Image as ImageIcon, Upload, Download, Loader2, Maximize2, RefreshCw } from 'lucide-vue-next'
const file=ref<File|null>(null), mode=ref<'resize'|'convert'>('resize'), width=ref(1200), height=ref(800), format=ref('jpg'), busy=ref(false), error=ref(''), resultUrl=ref('')
const api=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'')
const preview=computed(()=>file.value?URL.createObjectURL(file.value):'')
function choose(f:File|null){file.value=f;error.value='';if(resultUrl.value)URL.revokeObjectURL(resultUrl.value);resultUrl.value=''}
async function run(){if(!file.value){error.value='请先选择图片';return}busy.value=true;error.value='';try{const form=new FormData();form.append('file',file.value);const path=mode.value==='resize'?`/api/image/resize?width=${width.value}&height=${height.value}`:`/api/image/convert?format=${format.value}`;const r=await fetch(`${api}${path}`,{method:'POST',body:form});if(!r.ok)throw new Error(await r.text()||'图片处理失败');resultUrl.value=URL.createObjectURL(await r.blob())}catch(e){error.value=e instanceof Error?e.message:'图片处理失败'}finally{busy.value=false}}
onBeforeUnmount(()=>{if(resultUrl.value)URL.revokeObjectURL(resultUrl.value)})
</script>
<template><div class="image-tool"><div class="tabs"><button :class="{active:mode==='resize'}" @click="mode='resize'"><Maximize2 :size="16"/>调整尺寸</button><button :class="{active:mode==='convert'}" @click="mode='convert'"><RefreshCw :size="16"/>格式转换</button></div><div class="head"><div class="icon"><ImageIcon/></div><div><h1>{{mode==='resize'?'图片尺寸调整':'图片格式转换'}}</h1><p>{{mode==='resize'?'快速调整图片宽高并输出 JPG。':'将图片转换为 PNG / JPG 格式。'}}</p></div></div><label class="drop"><img v-if="preview" :src="preview"/><Upload v-else :size="24"/><b>{{file?file.name:'点击或拖拽图片到这里'}}</b><span>支持常见 JPG、PNG 图片</span><input type="file" accept="image/*" hidden @change="choose(($event.target as HTMLInputElement).files?.[0]||null)"/></label><div v-if="file" class="options"><template v-if="mode==='resize'"><label>宽度 <input v-model.number="width" type="number" min="1"/></label><label>高度 <input v-model.number="height" type="number" min="1"/></label></template><label v-else>输出格式 <select v-model="format"><option>jpg</option><option>png</option></select></label></div><div v-if="error" class="error">{{error}}</div><div class="actions"><button class="primary" :disabled="busy" @click="run"><Loader2 v-if="busy" class="spin"/><span>{{busy?'处理中…':'开始处理'}}</span></button><a v-if="resultUrl" class="download" :href="resultUrl" :download="mode==='resize'?'officebox-resized.jpg':`officebox-converted.${format}`"><Download :size="16"/>下载结果</a></div></div></template>
<style scoped>.image-tool{max-width:900px;margin:auto;padding:30px 24px}.tabs{display:flex;gap:6px;background:#f1f2f7;padding:5px;border-radius:11px;width:max-content}.tabs button{border:0;background:transparent;padding:9px 14px;border-radius:8px;display:flex;gap:7px;align-items:center;color:#7c8495;cursor:pointer;font-size:12px}.tabs button.active{background:#fff;color:#5f52d7;box-shadow:0 2px 7px #28345d12}.head{display:flex;align-items:center;gap:14px;margin:28px 0 20px}.icon{width:46px;height:46px;border-radius:12px;background:#e8f2ff;color:#4382d4;display:grid;place-items:center}.head h1{font-size:22px;margin:0 0 4px}.head p{font-size:12px;color:#8991a2;margin:0}.drop{min-height:190px;border:1.5px dashed #ccd1df;border-radius:15px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;color:#4382d4;background:#fbfdff;cursor:pointer}.drop img{max-width:180px;max-height:100px;border-radius:8px;object-fit:contain}.drop b{font-size:13px;color:#343c4c;max-width:90%;overflow:hidden;text-overflow:ellipsis}.drop span{font-size:11px;color:#969dad}.options{display:flex;gap:12px;margin-top:16px;padding:15px;border:1px solid #e7e9ef;border-radius:10px;background:#fff}.options label{font-size:12px;color:#687083;display:flex;align-items:center;gap:7px}.options input,.options select{width:110px;border:1px solid #dfe2ea;border-radius:7px;padding:7px;outline:none}.error{margin-top:14px;background:#fff0f0;color:#c84f5a;padding:10px;border-radius:8px;font-size:12px}.actions{display:flex;gap:9px;margin-top:20px}.primary,.download{border:0;border-radius:9px;padding:10px 15px;display:flex;align-items:center;gap:7px;font-size:12px;font-weight:650;text-decoration:none;cursor:pointer}.primary{background:#6659df;color:white}.download{background:#eaf7ef;color:#348354}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
</style>