<script setup lang="ts">
import { ref, computed, onBeforeUnmount } from 'vue'
import { Image as ImageIcon, Upload, Download, Loader2, Maximize2, RefreshCw, Minimize2, X } from 'lucide-vue-next'
const file=ref<File|null>(null), mode=ref<'compress'|'resize'|'convert'>('compress'), quality=ref('0.75'), scale=ref(100), width=ref(1200), height=ref(800), format=ref('jpg'), busy=ref(false), error=ref(''), resultUrl=ref(''), resultSize=ref(0)
const api=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'')
const preview=computed(()=>file.value?URL.createObjectURL(file.value):'')
const saving=computed(()=>file.value&&resultSize.value?Math.max(0,Math.round((1-resultSize.value/file.value.size)*100)):0)
function choose(f:File|null){file.value=f;error.value='';resultSize.value=0;if(resultUrl.value)URL.revokeObjectURL(resultUrl.value);resultUrl.value=''}
function clear(){choose(null)}
async function run(){if(!file.value){error.value='请先选择图片';return}busy.value=true;error.value='';try{const form=new FormData();form.append('file',file.value);let path='';if(mode.value==='compress')path=`/api/image/compress?quality=${quality.value}&scale=${scale.value}`;else if(mode.value==='resize')path=`/api/image/resize?width=${width.value}&height=${height.value}`;else path=`/api/image/convert?format=${format.value}`;const r=await fetch(`${api}${path}`,{method:'POST',body:form});if(!r.ok)throw new Error(await r.text()||'图片处理失败');const blob=await r.blob();resultSize.value=blob.size;resultUrl.value=URL.createObjectURL(blob)}catch(e){error.value=e instanceof Error?e.message:'图片处理失败'}finally{busy.value=false}}
function fmt(n:number){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(2)} MB`}
onBeforeUnmount(()=>{if(resultUrl.value)URL.revokeObjectURL(resultUrl.value)})
</script>
<template><div class="image-tool"><div class="tabs"><button :class="{active:mode==='compress'}" @click="mode='compress'"><Minimize2 :size="16"/>压缩图片</button><button :class="{active:mode==='resize'}" @click="mode='resize'"><Maximize2 :size="16"/>调整尺寸</button><button :class="{active:mode==='convert'}" @click="mode='convert'"><RefreshCw :size="16"/>格式转换</button></div><div class="head"><div class="icon"><ImageIcon/></div><div><h1>{{mode==='compress'?'图片压缩':mode==='resize'?'图片尺寸调整':'图片格式转换'}}</h1><p>{{mode==='compress'?'降低图片质量与尺寸，明显减小文件体积。':mode==='resize'?'快速调整图片宽高并输出 JPG。':'将图片转换为 PNG / JPG 格式。'}}</p></div></div><label class="drop"><img v-if="preview" :src="preview"/><Upload v-else :size="24"/><b>{{file?file.name:'点击或拖拽图片到这里'}}</b><span>支持 JPG、JPEG、PNG、WebP 等常见图片</span><input type="file" accept="image/*" hidden @change="choose(($event.target as HTMLInputElement).files?.[0]||null)"/></label><button v-if="file" class="remove" @click="clear"><X :size="14"/>移除图片</button><div v-if="file" class="options"><template v-if="mode==='compress'"><label>压缩质量<select v-model="quality"><option value="0.9">高质量</option><option value="0.75">推荐</option><option value="0.5">小体积</option></select></label><label>尺寸<select v-model.number="scale"><option :value="100">100%</option><option :value="75">75%</option><option :value="50">50%</option></select></label></template><template v-else-if="mode==='resize'"><label>宽度 <input v-model.number="width" type="number" min="1"/></label><label>高度 <input v-model.number="height" type="number" min="1"/></label></template><label v-else>输出格式 <select v-model="format"><option>jpg</option><option>png</option></select></label></div><div v-if="resultSize" class="result">原文件 {{fmt(file!.size)}} → 压缩后 {{fmt(resultSize)}} <b v-if="saving">节省 {{saving}}%</b></div><div v-if="error" class="error">{{error}}</div><div class="actions"><button class="primary" :disabled="busy" @click="run"><Loader2 v-if="busy" class="spin"/><span>{{busy?'处理中…':'开始处理'}}</span></button><a v-if="resultUrl" class="download" :href="resultUrl" :download="mode==='compress'?'officebox-compressed.jpg':mode==='resize'?'officebox-resized.jpg':`officebox-converted.${format}`"><Download :size="16"/>下载结果</a></div></div></template>
<style scoped>.image-tool{max-width:900px;margin:auto;padding:30px 24px}.tabs{display:flex;gap:6px;background:#f1f2f7;padding:5px;border-radius:11px;width:max-content}.tabs button{border:0;background:transparent;padding:9px 14px;border-radius:8px;display:flex;gap:7px;align-items:center;color:#7c8495;cursor:pointer;font-size:12px}.tabs button.active{background:#fff;color:#5f52d7;box-shadow:0 2px 7px #28345d12}.head{display:flex;align-items:center;gap:14px;margin:28px 0 20px}.icon{width:46px;height:46px;border-radius:12px;background:#e8f2ff;color:#4382d4;display:grid;place-items:center}.head h1{font-size:22px;margin:0 0 4px}.head p{font-size:12px;color:#8991a2;margin:0}.drop{min-height:190px;border:1.5px dashed #ccd1df;border-radius:15px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;color:#4382d4;background:#fbfdff;cursor:pointer}.drop img{max-width:180px;max-height:100px;border-radius:8px;object-fit:contain}.drop b{font-size:13px;color:#343c4c;max-width:90%;overflow:hidden;text-overflow:ellipsis}.drop span{font-size:11px;color:#969dad}.remove{margin:10px 0 0 auto;border:0;background:transparent;color:#c84f5a;display:flex;gap:5px;align-items:center;cursor:pointer;font-size:11px}.options{display:flex;gap:12px;margin-top:16px;padding:15px;border:1px solid #e7e9ef;border-radius:10px;background:#fff}.options label{font-size:12px;color:#687083;display:flex;align-items:center;gap:7px}.options input,.options select{width:110px;border:1px solid #dfe2ea;border-radius:7px;padding:7px;outline:none}.result{margin-top:14px;background:#f1f8f4;color:#348354;padding:10px;border-radius:8px;font-size:12px}.result b{margin-left:8px}.error{margin-top:14px;background:#fff0f0;color:#c84f5a;padding:10px;border-radius:8px;font-size:12px}.actions{display:flex;gap:9px;margin-top:20px}.primary,.download{border:0;border-radius:9px;padding:10px 15px;display:flex;align-items:center;gap:7px;font-size:12px;font-weight:650;text-decoration:none;cursor:pointer}.primary{background:#6659df;color:white}.download{background:#eaf7ef;color:#348354}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
</style>
