<script setup lang="ts">
import { ref } from 'vue'
import { ScanText, Upload, Download, Loader2, Copy, FileText } from 'lucide-vue-next'
const file=ref<File|null>(null), text=ref(''), busy=ref(false), error=ref(''), mode=ref<'image'|'pdf'>('image')
const api=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'')
function pick(e:Event){file.value=(e.target as HTMLInputElement).files?.[0]||null;text.value='';error.value=''}
async function run(){if(!file.value){error.value='请选择文件';return}busy.value=true;error.value='';try{const f=new FormData();f.append('file',file.value);f.append('lang','chi_sim+eng');const path=mode.value==='pdf'?'/api/ocr/pdf':'/api/ocr/image';const r=await fetch(`${api}${path}`,{method:'POST',body:f});if(!r.ok)throw Error(await r.text()||'OCR 失败');text.value=await r.text()}catch(e){error.value=e instanceof Error?e.message:'OCR 失败'}finally{busy.value=false}}
async function copy(){if(text.value)await navigator.clipboard.writeText(text.value)}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text.value],{type:'text/plain;charset=utf-8'}));a.download='officebox-ocr.txt';a.click()}
</script>
<template><div class="ocr"><div class="head"><div class="icon"><ScanText/></div><div><h1>OCR 文字识别</h1><p>图片与 PDF 中的中文、英文文字快速提取。</p></div></div><div class="tabs"><button :class="{active:mode==='image'}" @click="mode='image'">图片 OCR</button><button :class="{active:mode==='pdf'}" @click="mode='pdf'">PDF OCR</button></div><label class="drop"><Upload :size="25"/><b>{{file?file.name:mode==='pdf'?'选择 PDF':'选择图片'}}</b><span>{{mode==='pdf'?'最多处理前 50 页':'支持常见图片格式'}}</span><input type="file" :accept="mode==='pdf'?'.pdf':'image/*'" hidden @change="pick"/></label><button class="run" :disabled="busy||!file" @click="run"><Loader2 v-if="busy" class="spin"/><ScanText v-else :size="16"/> {{busy?'识别中…':'开始 OCR'}}</button><div v-if="error" class="error">{{error}}</div><div v-if="text" class="result"><div class="bar"><b>识别结果</b><span>{{text.length}} 字符</span><button @click="copy"><Copy :size="15"/>复制</button><button @click="download"><Download :size="15"/>TXT</button></div><textarea v-model="text" spellcheck="false"/></div></div></template>
<style scoped>.ocr{max-width:900px;margin:auto;padding:30px 24px}.head{display:flex;gap:14px;align-items:center;margin-bottom:18px}.icon{width:46px;height:46px;border-radius:12px;background:#fff1df;color:#d77922;display:grid;place-items:center}.head h1{font-size:22px;margin:0 0 4px}.head p,.drop span{font-size:12px;color:#8991a2}.tabs{display:flex;gap:6px;margin-bottom:12px}.tabs button{border:1px solid #e1e4ec;background:#fff;border-radius:8px;padding:8px 12px;cursor:pointer;font-size:12px}.tabs button.active{background:#6659df;color:#fff;border-color:#6659df}.drop{min-height:180px;border:1.5px dashed #ccd1df;border-radius:15px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:9px;cursor:pointer}.drop b{font-size:13px}.run{margin-top:18px;border:0;border-radius:9px;padding:10px 16px;background:#6659df;color:white;display:flex;gap:7px;align-items:center;cursor:pointer}.run:disabled{opacity:.5}.error{margin-top:14px;background:#fff0f0;color:#c84f5a;padding:10px;border-radius:8px;font-size:12px}.result{margin-top:18px;border:1px solid #e7e9ef;border-radius:10px;overflow:hidden}.bar{padding:10px;display:flex;gap:8px;align-items:center;border-bottom:1px solid #e7e9ef;font-size:12px}.bar span{color:#8991a2;flex:1}.bar button{border:0;background:#f3f4f7;border-radius:7px;padding:6px 9px;display:flex;gap:5px;align-items:center;cursor:pointer}textarea{display:block;width:100%;min-height:280px;border:0;padding:14px;resize:vertical;box-sizing:border-box;font:13px/1.6 sans-serif;outline:0}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}</style>