<script setup lang="ts">
import { ref } from 'vue'
import { FileText, Upload, Download, Loader2 } from 'lucide-vue-next'
const files=ref<File[]>([]), busy=ref(false), error=ref(''), url=ref(''), name=ref('officebox.pdf')
const api=(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'')
function pick(e:Event){files.value=Array.from((e.target as HTMLInputElement).files||[]);error.value='';if(url.value)URL.revokeObjectURL(url.value);url.value=''}
async function run(path:string, field='file', extra?:Record<string,string>){if(!files.value.length){error.value='请选择 PDF';return}busy.value=true;error.value='';try{const f=new FormData();if(field==='files')files.value.forEach(x=>f.append('files',x));else f.append(field,files.value[0]);Object.entries(extra||{}).forEach(([k,v])=>f.append(k,v));const r=await fetch(`${api}${path}`,{method:'POST',body:f});if(!r.ok)throw Error('PDF 操作失败');const b=await r.blob();url.value=URL.createObjectURL(b);name.value=path.includes('merge')?'officebox-merged.pdf':path.includes('rotate')?'officebox-rotated.pdf':'officebox-result.pdf'}catch(e){error.value=e instanceof Error?e.message:'PDF 操作失败'}finally{busy.value=false}}
</script>
<template><div class="pdf"><div class="head"><FileText/><div><h1>PDF 工具箱</h1><p>合并、旋转、页面提取、删除、水印、加密与解密。</p></div></div><label class="drop"><Upload :size="24"/><b>选择 PDF 文件</b><span>可多选，用于合并</span><input type="file" accept=".pdf" multiple hidden @change="pick"/></label><div v-if="files.length" class="info">已选择 {{files.length}} 个 PDF <span v-for="f in files" :key="f.name">{{f.name}}</span></div><div class="tools"><button @click="run('/api/pdf/merge','files')">合并</button><button :disabled="files.length!==1" @click="run('/api/pdf/rotate','file',{degrees:'90'})">旋转 90°</button><button :disabled="busy||!files.length" @click="run('/api/pdf/compress')">压缩</button><button :disabled="busy||!files.length" @click="run('/api/pdf/encrypt','file',{password:'officebox'})">加密</button></div><div v-if="error" class="error">{{error}}</div><a v-if="url" class="download" :href="url" :download="name"><Download :size="16"/>下载结果</a><Loader2 v-if="busy" class="spin"/></div></template>
<style scoped>.pdf{max-width:900px;margin:auto;padding:30px 24px}.head{display:flex;gap:14px;align-items:center;margin-bottom:22px}.head h1{margin:0 0 5px;font-size:22px}.head p,.drop span{color:#8991a2;font-size:12px}.drop{min-height:170px;border:1.5px dashed #ccd1df;border-radius:15px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:9px;cursor:pointer;color:#6659df}.drop b{color:#343c4c;font-size:13px}.info{margin:14px 0;font-size:12px}.info span{display:block;color:#8991a2;margin-top:4px}.tools{display:flex;flex-wrap:wrap;gap:9px;margin-top:18px}.tools button,.download{border:0;border-radius:9px;padding:10px 14px;background:#6659df;color:white;text-decoration:none;cursor:pointer}.error{margin-top:14px;padding:10px;border-radius:8px;background:#fff0f0;color:#c84f5a}.download{display:inline-flex;gap:7px;align-items:center;margin-top:18px;background:#eaf7ef;color:#348354}.spin{margin-top:16px;animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}</style>