package com.officebox.controller;
import org.apache.pdfbox.Loader;import org.apache.pdfbox.io.RandomAccessReadBuffer;import org.apache.pdfbox.multipdf.PDFMergerUtility;import org.apache.pdfbox.pdmodel.*;import org.springframework.http.MediaType;import org.springframework.http.ResponseEntity;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.io.ByteArrayOutputStream;import java.util.*;
@RestController @RequestMapping("/api/pdf")
public class PdfToolsController{
 @PostMapping(value="/merge",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<byte[]> merge(@RequestParam("files") MultipartFile[] files)throws Exception{
  if(files==null||files.length<2)return ResponseEntity.badRequest().build(); PDFMergerUtility merger=new PDFMergerUtility();List<RandomAccessReadBuffer> sources=new ArrayList<>();try{for(MultipartFile f:files){if(f!=null&&!f.isEmpty()){Loader.loadPDF(f.getBytes()).close();RandomAccessReadBuffer r=new RandomAccessReadBuffer(f.getInputStream());sources.add(r);merger.addSource(r);}}if(sources.size()<2)return ResponseEntity.badRequest().build();ByteArrayOutputStream out=new ByteArrayOutputStream();merger.setDestinationStream(out);merger.mergeDocuments(null);return pdf(out.toByteArray(),"officebox-merged.pdf");}finally{for(RandomAccessReadBuffer r:sources)try{r.close();}catch(Exception ignored){}}}
 @PostMapping(value="/rotate",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<byte[]> rotate(@RequestParam("file")MultipartFile file,@RequestParam(defaultValue="90")int degrees)throws Exception{if(file==null||file.isEmpty()||degrees%90!=0)return ResponseEntity.badRequest().build();int n=((degrees%360)+360)%360;try(PDDocument doc=Loader.loadPDF(file.getBytes());ByteArrayOutputStream out=new ByteArrayOutputStream()){for(PDPage p:doc.getPages())p.setRotation((p.getRotation()+n)%360);doc.save(out);return pdf(out.toByteArray(),"officebox-rotated.pdf");}}
 private ResponseEntity<byte[]> pdf(byte[] b,String n){return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header("Content-Disposition","attachment; filename=\""+n+"\"").body(b);}
}
