spring.application.name=officebox-api
server.port=${PORT:8080}
server.forward-headers-strategy=framework
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:100MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:500MB}
